config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # CRUD
  # C
  get '/tasks/new', to: 'tasks#new'
  post '/tasks/', to: 'tasks#create'

  # R
  get '/tasks', to: 'tasks#index' #read all
  get '/tasks/:id', to: 'tasks#show', as: :task #read one
  # U
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_tasks
  patch '/tasks/:id', to: 'tasks#update'
  # D
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    # @tasks = Task.find(params[:id])
    task = Task.new(tasks_params)
    task.save

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(tasks_params)

    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= fsimple_form_for(task) do |f| %>
  <div>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.submit %>
  </div>
<% end %>

<form class="simple_form new_task" id="new_task" novalidate="novalidate" action="/tasks" accept-charset="UTF-8" method="post">
  <input type="hidden" name="authenticity_token" value="6mcCvU7ZazpIBcJTptw/8y4EucmzccFWli7tFUzX6IJEx8wq6PFC7m4rA1Jy+W4YW1hlhYhSOyhZefWtOM5ofQ==">
  <div class="form-group string optional task_name">
    <label class="string optional" for="task_name">Title</label>
    <input class="form-control string optional" type="text" name="task[title]" id="task_name">
  </div>
  <div class="form-group string optional task_address">
    <label class="string optional" for="task_address">Details</label>
    <input class="form-control string optional" type="text" name="task[details]" id="task_address">
  </div>
  <input type="submit" name="commit" value="Create task" data-disable-with="Create task">
</form>

app/views/tasks/edit.html.erb
<h2>Edit <%= @task.title %></h2>

<%= render 'form' %>

<%= link_to 'back to list', tasks_path %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
  <li>
    <%= link_to task.title, task_path(task.id) %>
    </li>
  <% end %>
</ul>

<div>
  <%= link_to 'new task', tasks_new_path %>
</div>

<%= link_to "Delete",
task_path(@tasks),
method: :delete,
data: { confirm: "Are you sure?" } %>

<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/tasks/:id">
  Delete task
</a>

app/views/tasks/new.html.erb
<h2>Create a new task</h2>

<%= render 'form' %>

<%= link_to 'Back to', tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @tasks.title %></h2>
<h2><%= @tasks.details %></h2>
<div>
  <%= link_to 'edit task', edit_tasks_path %>
  <%= link_to 'Back to', tasks_path %>
</div>